package BufferApp;


// TODO: Auto-generated Javadoc
/**
* BufferApp/BufferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* martes 29 de noviembre de 2016 11H21' CET
*/

public interface BufferOperations 
{
  
  /**
   * Num elementos.
   *
   * @return El número de elementos
   */
  int num_elementos ();
  
  /**
   * Introduce elemento en la cola
   *
    * @param noticia la noticia a insertar
   * @return true, if successful
   */
    boolean put (BufferApp.Noticia noticia);
  
  /**
   * Saca el primer elemento de la cola
   *
    * @param noticia la noticia
   * @return true, if successful
   */
    boolean get (BufferApp.NoticiaHolder noticia);
  
  /**
   * Lee el primer elemento de la cola
   *
    * @param noticia la noticia
   * @return true, if successful
   */
    boolean read (BufferApp.NoticiaHolder noticia);

    /**
    * Fija el limite maximo de noticias permitido en el buffer.
    *
    * @param numero_maximo nuevo limite maximo
    */
    void fijarLimiteNoticias (int numero_maximo);
  
  /**
   * Apaga el servidor Corba
   */
  void shutdown ();
} // interface BufferOperations
